[2025-03-28T19:42:55.615+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initDB.initdata manual__2025-03-28T19:42:54.497091+00:00 [queued]>
[2025-03-28T19:42:55.622+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initDB.initdata manual__2025-03-28T19:42:54.497091+00:00 [queued]>
[2025-03-28T19:42:55.622+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-03-28T19:42:55.636+0000] {taskinstance.py:2217} INFO - Executing <Task(PostgresOperator): initdata> on 2025-03-28 19:42:54.497091+00:00
[2025-03-28T19:42:55.641+0000] {standard_task_runner.py:60} INFO - Started process 869 to run task
[2025-03-28T19:42:55.643+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'initDB', 'initdata', 'manual__2025-03-28T19:42:54.497091+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ArsenalDag.py', '--cfg-path', '/tmp/tmpt3zyfa17']
[2025-03-28T19:42:55.645+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask initdata
[2025-03-28T19:42:55.655+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-28T19:42:55.677+0000] {task_command.py:423} INFO - Running <TaskInstance: initDB.initdata manual__2025-03-28T19:42:54.497091+00:00 [running]> on host d87fcbd51e2e
[2025-03-28T19:42:55.726+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='initDB' AIRFLOW_CTX_TASK_ID='initdata' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T19:42:54.497091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T19:42:54.497091+00:00'
[2025-03-28T19:42:55.726+0000] {sql.py:276} INFO - Executing: 
            create table hema(
                name varchar(50),
                id int
            );
        
[2025-03-28T19:42:55.732+0000] {base.py:83} INFO - Using connection ID '***_conn' for task execution.
[2025-03-28T19:42:55.739+0000] {base.py:83} INFO - Using connection ID '***_conn' for task execution.
[2025-03-28T19:42:55.744+0000] {sql.py:457} INFO - Running statement: 
            create table hema(
                name varchar(50),
                id int
            );
        , parameters: None
[2025-03-28T19:42:55.744+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "hema" already exists

[2025-03-28T19:42:55.750+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=initDB, task_id=initdata, execution_date=20250328T194254, start_date=20250328T194255, end_date=20250328T194255
[2025-03-28T19:42:55.759+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task initdata (relation "hema" already exists
; 869)
[2025-03-28T19:42:55.775+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-28T19:42:55.787+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
