[2025-03-28T17:24:22.069+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_arsenal_postgres.load_data_to_postgres manual__2025-03-28T17:19:18.107542+00:00 [queued]>
[2025-03-28T17:24:22.087+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_arsenal_postgres.load_data_to_postgres manual__2025-03-28T17:19:18.107542+00:00 [queued]>
[2025-03-28T17:24:22.088+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-03-28T17:24:22.120+0000] {taskinstance.py:2217} INFO - Executing <Task(SparkSubmitOperator): load_data_to_postgres> on 2025-03-28 17:19:18.107542+00:00
[2025-03-28T17:24:22.133+0000] {standard_task_runner.py:60} INFO - Started process 1399 to run task
[2025-03-28T17:24:22.139+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_arsenal_postgres', 'load_data_to_postgres', 'manual__2025-03-28T17:19:18.107542+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/ArsenalDag.py', '--cfg-path', '/tmp/tmpmc0b9bbf']
[2025-03-28T17:24:22.143+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask load_data_to_postgres
[2025-03-28T17:24:22.177+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-28T17:24:22.242+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_arsenal_postgres.load_data_to_postgres manual__2025-03-28T17:19:18.107542+00:00 [running]> on host d87fcbd51e2e
[2025-03-28T17:24:22.405+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_arsenal_postgres' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T17:19:18.107542+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T17:19:18.107542+00:00'
[2025-03-28T17:24:22.423+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2025-03-28T17:24:22.425+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://master:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/***/spark/app/Extract.py --postgres_host postgres --postgres_port 5432 --postgres_db mydatabase --postgres_user postgres --postgres_password ******
[2025-03-28T17:24:22.540+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-28T17:24:25.526+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-28T17:24:27.456+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SparkContext: Running Spark version 3.5.5
[2025-03-28T17:24:27.457+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SparkContext: OS info Linux, 6.8.0-55-generic, amd64
[2025-03-28T17:24:27.458+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SparkContext: Java version 17.0.14
[2025-03-28T17:24:27.520+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO ResourceUtils: ==============================================================
[2025-03-28T17:24:27.521+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-28T17:24:27.522+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO ResourceUtils: ==============================================================
[2025-03-28T17:24:27.523+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SparkContext: Submitted application: Arsenal_ETL
[2025-03-28T17:24:27.574+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-28T17:24:27.591+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO ResourceProfile: Limiting resource is cpu
[2025-03-28T17:24:27.592+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-28T17:24:27.699+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SecurityManager: Changing view acls to: ***
[2025-03-28T17:24:27.700+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SecurityManager: Changing modify acls to: ***
[2025-03-28T17:24:27.700+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SecurityManager: Changing view acls groups to:
[2025-03-28T17:24:27.701+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SecurityManager: Changing modify acls groups to:
[2025-03-28T17:24:27.702+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:27 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-28T17:24:28.105+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO Utils: Successfully started service 'sparkDriver' on port 33757.
[2025-03-28T17:24:28.157+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO SparkEnv: Registering MapOutputTracker
[2025-03-28T17:24:28.211+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-28T17:24:28.249+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-28T17:24:28.250+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-28T17:24:28.261+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-28T17:24:28.310+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-867a52e2-3a1a-4c7b-b29d-47285da7313f
[2025-03-28T17:24:28.331+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-28T17:24:28.351+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-28T17:24:28.532+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-28T17:24:28.625+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-28T17:24:28.675+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO SparkContext: Added JAR /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar at spark://d87fcbd51e2e:33757/jars/postgresql-42.7.3.jar with timestamp 1743182667438
[2025-03-28T17:24:28.753+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://master:7077...
[2025-03-28T17:24:28.800+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:28 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master master:7077
[2025-03-28T17:24:28.801+0000] {spark_submit.py:488} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-28T17:24:28.801+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-28T17:24:28.801+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-03-28T17:24:28.802+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T17:24:28.803+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T17:24:28.803+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T17:24:28.803+0000] {spark_submit.py:488} INFO - Caused by: java.io.IOException: Failed to connect to master/<unresolved>:7077
[2025-03-28T17:24:28.803+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2025-03-28T17:24:28.803+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2025-03-28T17:24:28.803+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - ... 4 more
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - Caused by: java.net.UnknownHostException: master
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
[2025-03-28T17:24:28.804+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2025-03-28T17:24:28.805+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
[2025-03-28T17:24:28.805+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2025-03-28T17:24:28.805+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2025-03-28T17:24:28.805+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2025-03-28T17:24:28.805+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2025-03-28T17:24:28.805+0000] {spark_submit.py:488} INFO - at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[2025-03-28T17:24:28.806+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2025-03-28T17:24:28.806+0000] {spark_submit.py:488} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2025-03-28T17:24:28.806+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2025-03-28T17:24:28.806+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2025-03-28T17:24:28.806+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2025-03-28T17:24:28.806+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[2025-03-28T17:24:28.807+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[2025-03-28T17:24:28.808+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[2025-03-28T17:24:28.808+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[2025-03-28T17:24:28.808+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
[2025-03-28T17:24:28.808+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
[2025-03-28T17:24:28.808+0000] {spark_submit.py:488} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2025-03-28T17:24:28.808+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2025-03-28T17:24:28.809+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2025-03-28T17:24:28.809+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2025-03-28T17:24:28.809+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2025-03-28T17:24:28.809+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[2025-03-28T17:24:28.809+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[2025-03-28T17:24:28.810+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[2025-03-28T17:24:28.810+0000] {spark_submit.py:488} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[2025-03-28T17:24:28.810+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2025-03-28T17:24:28.810+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2025-03-28T17:24:28.810+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2025-03-28T17:24:28.810+0000] {spark_submit.py:488} INFO - ... 1 more
[2025-03-28T17:24:48.754+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:48 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://master:7077...
[2025-03-28T17:24:48.765+0000] {spark_submit.py:488} INFO - 25/03/28 17:24:48 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master master:7077
[2025-03-28T17:24:48.766+0000] {spark_submit.py:488} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-28T17:24:48.767+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-28T17:24:48.767+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-28T17:24:48.767+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-03-28T17:24:48.768+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2025-03-28T17:24:48.768+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2025-03-28T17:24:48.769+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2025-03-28T17:24:48.769+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2025-03-28T17:24:48.769+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-03-28T17:24:48.770+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T17:24:48.770+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T17:24:48.771+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T17:24:48.771+0000] {spark_submit.py:488} INFO - Caused by: java.io.IOException: Failed to connect to master/<unresolved>:7077
[2025-03-28T17:24:48.771+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2025-03-28T17:24:48.772+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2025-03-28T17:24:48.772+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2025-03-28T17:24:48.772+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2025-03-28T17:24:48.772+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2025-03-28T17:24:48.773+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2025-03-28T17:24:48.773+0000] {spark_submit.py:488} INFO - ... 4 more
[2025-03-28T17:24:48.773+0000] {spark_submit.py:488} INFO - Caused by: java.net.UnknownHostException: master
[2025-03-28T17:24:48.774+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
[2025-03-28T17:24:48.774+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2025-03-28T17:24:48.774+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
[2025-03-28T17:24:48.775+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2025-03-28T17:24:48.775+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2025-03-28T17:24:48.775+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2025-03-28T17:24:48.776+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2025-03-28T17:24:48.776+0000] {spark_submit.py:488} INFO - at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[2025-03-28T17:24:48.777+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2025-03-28T17:24:48.777+0000] {spark_submit.py:488} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2025-03-28T17:24:48.777+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2025-03-28T17:24:48.778+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2025-03-28T17:24:48.778+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2025-03-28T17:24:48.779+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2025-03-28T17:24:48.779+0000] {spark_submit.py:488} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2025-03-28T17:24:48.779+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
[2025-03-28T17:24:48.780+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2025-03-28T17:24:48.780+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
[2025-03-28T17:24:48.780+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
[2025-03-28T17:24:48.780+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[2025-03-28T17:24:48.781+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[2025-03-28T17:24:48.781+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[2025-03-28T17:24:48.782+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[2025-03-28T17:24:48.782+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
[2025-03-28T17:24:48.782+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
[2025-03-28T17:24:48.783+0000] {spark_submit.py:488} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2025-03-28T17:24:48.783+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2025-03-28T17:24:48.783+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2025-03-28T17:24:48.784+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2025-03-28T17:24:48.784+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2025-03-28T17:24:48.784+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[2025-03-28T17:24:48.785+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[2025-03-28T17:24:48.785+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[2025-03-28T17:24:48.785+0000] {spark_submit.py:488} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[2025-03-28T17:24:48.786+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2025-03-28T17:24:48.786+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2025-03-28T17:24:48.786+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2025-03-28T17:24:48.787+0000] {spark_submit.py:488} INFO - ... 1 more
[2025-03-28T17:25:08.754+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:08 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://master:7077...
[2025-03-28T17:25:08.765+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:08 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master master:7077
[2025-03-28T17:25:08.766+0000] {spark_submit.py:488} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-03-28T17:25:08.767+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-03-28T17:25:08.767+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-03-28T17:25:08.767+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-03-28T17:25:08.768+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2025-03-28T17:25:08.768+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2025-03-28T17:25:08.768+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2025-03-28T17:25:08.768+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2025-03-28T17:25:08.769+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-03-28T17:25:08.769+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T17:25:08.769+0000] {spark_submit.py:488} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T17:25:08.769+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T17:25:08.770+0000] {spark_submit.py:488} INFO - Caused by: java.io.IOException: Failed to connect to master/<unresolved>:7077
[2025-03-28T17:25:08.770+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2025-03-28T17:25:08.771+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2025-03-28T17:25:08.771+0000] {spark_submit.py:488} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2025-03-28T17:25:08.771+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2025-03-28T17:25:08.772+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2025-03-28T17:25:08.772+0000] {spark_submit.py:488} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2025-03-28T17:25:08.772+0000] {spark_submit.py:488} INFO - ... 4 more
[2025-03-28T17:25:08.773+0000] {spark_submit.py:488} INFO - Caused by: java.net.UnknownHostException: master
[2025-03-28T17:25:08.773+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
[2025-03-28T17:25:08.773+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2025-03-28T17:25:08.774+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
[2025-03-28T17:25:08.774+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2025-03-28T17:25:08.774+0000] {spark_submit.py:488} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2025-03-28T17:25:08.774+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2025-03-28T17:25:08.775+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2025-03-28T17:25:08.775+0000] {spark_submit.py:488} INFO - at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[2025-03-28T17:25:08.775+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2025-03-28T17:25:08.775+0000] {spark_submit.py:488} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2025-03-28T17:25:08.776+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2025-03-28T17:25:08.776+0000] {spark_submit.py:488} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2025-03-28T17:25:08.776+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2025-03-28T17:25:08.777+0000] {spark_submit.py:488} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2025-03-28T17:25:08.777+0000] {spark_submit.py:488} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2025-03-28T17:25:08.777+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
[2025-03-28T17:25:08.778+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2025-03-28T17:25:08.778+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
[2025-03-28T17:25:08.778+0000] {spark_submit.py:488} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
[2025-03-28T17:25:08.779+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[2025-03-28T17:25:08.779+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[2025-03-28T17:25:08.779+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[2025-03-28T17:25:08.780+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[2025-03-28T17:25:08.780+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
[2025-03-28T17:25:08.780+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
[2025-03-28T17:25:08.781+0000] {spark_submit.py:488} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2025-03-28T17:25:08.781+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2025-03-28T17:25:08.781+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2025-03-28T17:25:08.782+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2025-03-28T17:25:08.782+0000] {spark_submit.py:488} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2025-03-28T17:25:08.782+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[2025-03-28T17:25:08.783+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[2025-03-28T17:25:08.783+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[2025-03-28T17:25:08.783+0000] {spark_submit.py:488} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[2025-03-28T17:25:08.784+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2025-03-28T17:25:08.784+0000] {spark_submit.py:488} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2025-03-28T17:25:08.785+0000] {spark_submit.py:488} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2025-03-28T17:25:08.785+0000] {spark_submit.py:488} INFO - ... 1 more
[2025-03-28T17:25:28.756+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2025-03-28T17:25:28.757+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2025-03-28T17:25:28.781+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34751.
[2025-03-28T17:25:28.781+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO NettyBlockTransferService: Server created on d87fcbd51e2e:34751
[2025-03-28T17:25:28.785+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-28T17:25:28.796+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, d87fcbd51e2e, 34751, None)
[2025-03-28T17:25:28.802+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO BlockManagerMasterEndpoint: Registering block manager d87fcbd51e2e:34751 with 434.4 MiB RAM, BlockManagerId(driver, d87fcbd51e2e, 34751, None)
[2025-03-28T17:25:28.805+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, d87fcbd51e2e, 34751, None)
[2025-03-28T17:25:28.807+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:28 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, d87fcbd51e2e, 34751, None)
[2025-03-28T17:25:29.126+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-28T17:25:29.470+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-28T17:25:29.474+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-28T17:25:29.550+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-28T17:25:29.570+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO SparkUI: Stopped Spark web UI at http://d87fcbd51e2e:4040
[2025-03-28T17:25:29.585+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-28T17:25:29.592+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-28T17:25:29.600+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2025-03-28T17:25:29.614+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-28T17:25:29.643+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO MemoryStore: MemoryStore cleared
[2025-03-28T17:25:29.644+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO BlockManager: BlockManager stopped
[2025-03-28T17:25:29.657+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-28T17:25:29.660+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-28T17:25:29.678+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:29 INFO SparkContext: Successfully stopped SparkContext
[2025-03-28T17:25:30.706+0000] {spark_submit.py:488} INFO - Traceback (most recent call last):
[2025-03-28T17:25:30.707+0000] {spark_submit.py:488} INFO - File "/opt/***/spark/app/Extract.py", line 44, in <module>
[2025-03-28T17:25:30.707+0000] {spark_submit.py:488} INFO - main()
[2025-03-28T17:25:30.708+0000] {spark_submit.py:488} INFO - File "/opt/***/spark/app/Extract.py", line 39, in main
[2025-03-28T17:25:30.708+0000] {spark_submit.py:488} INFO - read_and_write_csv_to_postgres(spark, matches_csv_path, matches_db_table)
[2025-03-28T17:25:30.708+0000] {spark_submit.py:488} INFO - File "/opt/***/spark/app/Extract.py", line 14, in read_and_write_csv_to_postgres
[2025-03-28T17:25:30.709+0000] {spark_submit.py:488} INFO - df = spark.read.csv(csv_path, header=True)
[2025-03-28T17:25:30.709+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-03-28T17:25:30.709+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.8/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-28T17:25:30.710+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.8/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-28T17:25:30.721+0000] {spark_submit.py:488} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/***/data/matches.csv.
[2025-03-28T17:25:30.791+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:30 INFO ShutdownHookManager: Shutdown hook called
[2025-03-28T17:25:30.792+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-b056f2ac-fdeb-48e6-8911-a894e52c1e2b
[2025-03-28T17:25:30.803+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-b056f2ac-fdeb-48e6-8911-a894e52c1e2b/pyspark-23da56e8-f6c6-44a9-8f5a-2386406cc9c6
[2025-03-28T17:25:30.812+0000] {spark_submit.py:488} INFO - 25/03/28 17:25:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-8e5d36b8-6539-42a1-b005-2f65c2e8197c
[2025-03-28T17:25:30.914+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://master:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/***/spark/app/Extract.py --postgres_host postgres --postgres_port 5432 --postgres_db mydatabase --postgres_user postgres --postgres_password ******. Error code is: 1.
[2025-03-28T17:25:30.919+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=etl_arsenal_postgres, task_id=load_data_to_postgres, execution_date=20250328T171918, start_date=20250328T172422, end_date=20250328T172530
[2025-03-28T17:25:30.948+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task load_data_to_postgres (Cannot execute: spark-submit --master spark://master:7077 --jars /Drivers/SQL_Sever/jdbc/postgresql-42.7.3.jar --name arrow-spark /opt/***/spark/app/Extract.py --postgres_host postgres --postgres_port 5432 --postgres_db mydatabase --postgres_user postgres --postgres_password ******. Error code is: 1.; 1399)
[2025-03-28T17:25:30.963+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-28T17:25:30.991+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
